# -- 코드를 입력하세요
# SELECT 
# C.HISTORY_ID, 
# CASE
#     WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >=90 THEN ROUND(A.DAILY_FEE*(DATEDIFF(C.END_DATE, C.START_DATE)+1)*0.9)
#     WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >=30 THEN ROUND(A.DAILY_FEE*(DATEDIFF(C.END_DATE, C.START_DATE)+1)*0.93)
#     WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >= 7 THEN ROUND(A.DAILY_FEE*(DATEDIFF(C.END_DATE, C.START_DATE)+1)*0.95)
#     ELSE ROUND(A.DAILY_FEE*(DATEDIFF(C.END_DATE, C.START_DATE)+1))
# END AS FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
# AND A.CAR_TYPE='트럭'
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C ON A.CAR_ID = C.CAR_ID
# GROUP BY HISTORY_ID
# ORDER BY FEE DESC, HISTORY_ID DESC;

SELECT 
    C.HISTORY_ID,
    ROUND(
        A.DAILY_FEE * (DATEDIFF(C.END_DATE, C.START_DATE)+1) *
        CASE
            WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >= 90 THEN 1 - B_90.DISCOUNT_RATE/100
            WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >= 30 THEN 1 - B_30.DISCOUNT_RATE/100
            WHEN DATEDIFF(C.END_DATE, C.START_DATE)+1 >= 7 THEN 1 - B_7.DISCOUNT_RATE/100
            ELSE 1
        END
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C ON A.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B_7  ON A.CAR_TYPE = B_7.CAR_TYPE AND B_7.DURATION_TYPE='7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B_30 ON A.CAR_TYPE = B_30.CAR_TYPE AND B_30.DURATION_TYPE='30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B_90 ON A.CAR_TYPE = B_90.CAR_TYPE AND B_90.DURATION_TYPE='90일 이상'
WHERE A.CAR_TYPE='트럭'
ORDER BY FEE DESC, C.HISTORY_ID DESC;