# 대여가 없는 차도 포함해야 한다
SELECT A.CAR_ID, A.CAR_TYPE,
ROUND(A.DAILY_FEE*30*(1-C.DISCOUNT_RATE/100)) AS FEE

FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE

WHERE A.CAR_TYPE IN ('SUV', '세단')
AND C.DURATION_TYPE='30일 이상'
AND A.CAR_ID NOT IN 
    (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-11-30'
    )
GROUP BY CAR_ID
HAVING FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;