-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, 
SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
-- 생산일자가 2022년 5월
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
-- 총매출 기준 내림차순, 식품 ID기준 오름차순
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;